### Get all products
GET http://localhost/product/all

### Add a product
POST http://localhost/product/add
content-type: application/json

{
    "name": "tablet",
    "price": 15,
    "stock": 100,
    "userId": 1
}

### Update a product
PUT http://localhost/product/update/2
content-type: application/json

{
    "name": "razor blade V2",
    "price": 119,
    "stock": 1000,
    "userId": 1
}

### Delete a product
DELETE http://localhost/product/delete/3