### ADMIN Signup / Register
POST http://localhost/auth/signup
content-type: application/json

{
    "name": "Alexis Amadei",
    "email": "alexis@amadei.fr",
    "password": "password",
    "admin": true
}
